///////////////////////////////////////////////////////////
// realms.inc
//
// Constants for realm data.
///////////////////////////////////////////////////////////

const REALM_BRITANNIA_START_X := 0;
const REALM_BRITANNIA_START_Y := 0;
const REALM_BRITANNIA_START_Z := -128;
const REALM_BRITANNIA_END_X := 7168;
const REALM_BRITANNIA_END_Y := 4096;
const REALM_BRITANNIA_END_Z := 128;
const REALM_BRITANNIA_PLAYABLE_X := 6144;
const REALM_BRITANNIA_PLAYABLE_Y := REALM_BRITANNIA_END_Y;