version: '3.4'

services:
    zha:
        build: .
        container_name: polserver
        image: docker.pkg.github.com/zuluhotelaustralia/zha/server:latest
        hostname: shard.zuluhotel.com.au
        restart: unless-stopped
        #command: ["bash", "-c", "tail -f /dev/null"]
        ports:
            - 5003:5003
            - 5333:5333
        environment:
            - SERVER_EXTERNAL_IP
        volumes:
            - ../shard/:/shard
