const HATCH_DIFF_MOD:= 55;			// Difficulty (animallore) = Rating + this
const MAX_MATES:=3;				// Max number of times an osty can mate
const MIN_TIME_BETWEEN_BREEDING:=1200; 		// Seconds required to elapse between mating
const MATING_DIFF_MOD:=50;			// Difficulty (taming) = average of parents' ratings + this
const INCUBATION_PERIOD:=600;			// Seconds required to elapse before hatching
const TAME_DIFF_MOD:=55;			// Taming diff = Rating + this