// ** Bard Songs **
// Song of Awakening
const SPELL_ID_SONGAWAKENING:=129;
const MOVING_SPELL_SONGAWAKENING:=0;
const FX_SPELL_SONGAWAKENING:= 4435;
const SPEED_SPELL_SONGAWAKENING:= 10;
const LOOP_SPELL_SONGAWAKENING:= 10;
const SFX_SPELL_SONGAWAKENING:=69;

// ** Druid Spells **
// Spy wisp
const SPELL_ID_SPYWISP		:=145;
const SFX_SPELL_SPYWISP		:=0x1d3;
// Angry fock
const SPELL_ID_ANGRYFLOCK	:=146;
const SFX_SPELL_ANGRYFLOCK	:=0x1d3;
// Call Beast
const SPELL_ID_CALLBEAST	:=147;
const SFX_SPELL_CALLBEAST	:=0x3fc;
// Acid Splash
const SPELL_ID_ACIDSPLASH	:=148;
const SFX_SPELL_ACIDSPLASH	:=0x28;
const FX_SPELL_ACIDSPLASH	:=0x11AA;
const SPEED_SPELL_ACIDSPLASH	:= 10;
const LOOP_SPELL_ACIDSPLASH	:= 0;
// Goodberry
const SPELL_ID_GOODBERRY	:=149;
const SFX_SPELL_GOODBERRY	:= 0x340;
const FX_SPELL_GOODBERRY	:= 0x3735;
const SPEED_SPELL_GOODBERRY	:= 7;
const LOOP_SPELL_GOODBERRY	:= 7;
// Beastform
const SPELL_ID_BEASTFORM	:=150;
const SFX_SPELL_BEASTFORM	:=0x213;
const FX_SPELL_BEASTFORM	:=0x1ED9;
const SPEED_SPELL_BEASTFORM	:= 255;
const LOOP_SPELL_BEASTFORM	:= 15;
// Tree Hiding
const SPELL_ID_TREEHIDING	:=151;
const SFX_SPELL_TREEHIDING	:= 0x29E;
// Burning Fire
const SPELL_ID_BURNINGFIRE	:=152;
const SFX_SPELL_BURNINGFIRE	:= 0x349;
const FX_SPELL_BURNINGFIRE	:= 0x1A75;
const SPEED_SPELL_BURNINGFIRE	:= 255;
const LOOP_SPELL_BURNINGFIRE	:= 20;
const SFX_SPELL_BURNINGFIRE2	:= 0x358;
const FX_SPELL_BURNINGFIRE2	:= 0x36F4;
const SPEED_SPELL_BURNINGFIRE2	:= 7;
const LOOP_SPELL_BURNINGFIRE2	:= 1;
// Binding Nature
const SPELL_ID_BINDINGNATURE	:=153;
const SFX_SPELL_BINDINGNATURE	:= 0xA;
const FX_SPELL_BINDINGNATURE	:= 0x322C;
const SPEED_SPELL_BINDINGNATURE	:= 255;
const LOOP_SPELL_BINDINGNATURE	:= 20;
// Ferocious Wind
const SPELL_ID_FEROCIOUSWIND	:=154;
const SFX_SPELL_FEROCIOUSWIND	:=0x16;
const FX_SPELL_FEROCIOUSWIND	:=0x1B01; // Dmg on person
const SPEED_SPELL_FEROCIOUSWIND	:= 255;
const LOOP_SPELL_FEROCIOUSWIND	:= 13;
const FX_SPELL_FEROCIOUSWIND2	:=0x1B1F; // Leaves blowing in wind
const SPEED_SPELL_FEROCIOUSWIND2:= 1;
const LOOP_SPELL_FEROCIOUSWIND2	:= 0;
// Mother Nature
const SPELL_ID_MOTHERNATURE	:=155;
const SFX_SPELL_MOTHERNATURE	:= 0x2F7;
const FX_SPELL_MOTHERNATURE	:= 0x1153;
const SPEED_SPELL_MOTHERNATURE	:= 255;
const LOOP_SPELL_MOTHERNATURE	:= 13;
// Hail Storm
const SPELL_ID_HAILSTORM	:=156;
const SFX_SPELL_HAILSTORM	:= 0x118;
const FX_SPELL_HAILSTORM	:= 0x232E;
const SPEED_SPELL_HAILSTORM	:= 4;
const LOOP_SPELL_HAILSTORM	:= 0;
const FX_SPELL_HAILSTORM2	:= 0x232F;
// Summon Ostard
const SPELL_ID_SUMMONOSTARD	:=157;
const SFX_SPELL_SUMMONOSTARD	:= 0x2AC;
const FX_SPELL_SUMMONOSTARD	:= 0x322C;
const SPEED_SPELL_SUMMONOSTARD	:= 255;
const LOOP_SPELL_SUMMONOSTARD	:= 14;
// Resurrect Animal
const SPELL_ID_RESURRECTANIMAL	:=158;
const SFX_SPELL_RESURRECTANIMAL	:= 0x215;
const FX_SPELL_RESURRECTANIMAL	:= 0x1FDE;
const SPEED_SPELL_RESURRECTANIMAL:= 255;
const LOOP_SPELL_RESURRECTANIMAL:= 15;
// Acid Rain
const SPELL_ID_ACIDRAIN		:=159;
const SFX_SPELL_ACIDRAIN	:= 0x12;
const SFX_SPELL_ACIDRAIN2	:= 0x207;
const FX_SPELL_ACIDRAIN		:= 0x11AA;
const SPEED_SPELL_ACIDRAIN	:= 10;
const LOOP_SPELL_ACIDRAIN	:= 5;
// Personalize Mount
const SPELL_ID_PERSONALIZEMOUNT	:=160;
const SFX_SPELL_PERSONALIZEMOUNT:= 0x21;
const FX_SPELL_PERSONALIZEMOUNT	:= 0x36D4;
const SPEED_SPELL_PERSONALIZEMOUNT:= 2;
const LOOP_SPELL_PERSONALIZEMOUNT:= 10;

// ** Holy Spells **
// Communion
const SPELL_ID_COMMUNION	:= 161;
const SFX_SPELL_COMMUNION	:= 0xFF;
const FX_SPELL_COMMUNION	:= 0x3779;
const SPEED_SPELL_COMMUNION	:= 255;
const LOOP_SPELL_COMMUNION	:= 15;
// Last Rites
const SPELL_ID_LASTRITES	:= 162;
const SFX_SPELL_LASTRITES	:= 0x103;
// Detect Curse
const SPELL_ID_DETECTCURSE	:= 163;
const SFX_SPELL_DETECTCURSE	:= 0x2DA;
// Projected Light
const SPELL_ID_PROJECTEDLIGHT	:= 164;
const SFX_SPELL_PROJECTEDLIGHT	:= 0x55;
const FX_SPELL_PROJECTEDLIGHT	:= 0x22C6;
const SPEED_SPELL_PROJECTEDLIGHT:= 20;
const LOOP_SPELL_PROJECTEDLIGHT	:= 0;
// Town Portal
const SPELL_ID_TOWNPORTAL	:= 166;
const SFX_TOWNPORTAL 		:= 0x20F;
const COLOUR_TOWNPORTAL 	:= 1380;
// Negate Curse
const SPELL_ID_NEGATECURSE	:= 166;
const SFX_SPELL_NEGATECURSE	:=0x1E4;
const FX_SPELL_NEGATECURSE	:=0x1ED9;
const SPEED_SPELL_NEGATECURSE	:= 255;
const LOOP_SPELL_NEGATECURSE	:= 15;
// Regeneration
const SPELL_ID_REGENERATION	:= 167;
const SFX_SPELL_REGENERATION	:= 0x1ED;
const FX_SPELL_REGENERATION	:= 0x1FA3;
const SPEED_SPELL_REGENERATION	:= 255;
const LOOP_SPELL_REGENERATION	:= 14;
// Smite
const SPELL_ID_SMITE		:= 168;
const SFX_SPELL_SMITE		:= 0x1EA;
const FX_SPELL_SMITE		:= 0x2565;
const SPEED_SPELL_SMITE		:= 7;
const LOOP_SPELL_SMITE		:= 3;
// Radiating Armor
const SPELL_ID_RADIATINGARMOR	:= 169;
const SFX_SPELL_RADIATINGARMOR	:= 0x237;
const FX_SPELL_RADIATINGARMOR	:= 0x91E;
const SPEED_SPELL_RADIATINGARMOR:= 255;
const LOOP_SPELL_RADIATINGARMOR	:= 24;
// Devine Bless
const SPELL_ID_DEVINEBLESS	:= 170;
const SFX_SPELL_DEVINEBLESS	:= 0x103;
const FX_SPELL_DEVINEBLESS	:= 0x1153;
const SPEED_SPELL_DEVINEBLESS	:= 255;
const LOOP_SPELL_DEVINEBLESS	:= 20;
// Summon Angel
const SPELL_ID_SUMMONANGEL	:= 171;
// Mass Heal
const SPELL_ID_MASSHEAL		:= 172;
const SFX_SPELL_MASSHEAL	:= 0x0203;
const FX_SPELL_MASSHEAL		:= 0x375a;
const SPEED_SPELL_MASSHEAL	:= 7;
const LOOP_SPELL_MASSHEAL	:= 0x10;
// Life Stream
const SPELL_ID_LIFESTREAM	:= 173;
const SFX_LIFESTREAM 		:= 0x20F;
// Full Heal
const SPELL_ID_FULLHEAL		:= 174;
const SFX_SPELL_FULLHEAL	:= 0x0203;
const FX_SPELL_FULLHEAL		:= 0x3979;
const SPEED_SPELL_FULLHEAL	:= 25;
const LOOP_SPELL_FULLHEAL	:= 0x10;
// Holy Vengeance
const SPELL_ID_HOLYVENGEANCE	:= 175;
const SFX_SPELL_HOLYVENGEANCE	:= 0x2F8;
const SFX_SPELL_HOLYVENGEANCE2	:= 0x209;
const FX_SPELL_HOLYVENGEANCE	:= 0x3709;
const SPEED_SPELL_HOLYVENGEANCE	:= 0x0a;
const LOOP_SPELL_HOLYVENGEANCE	:= 0x1e;
// Purify
const SPELL_ID_PURIFY		:= 176;
const SFX_SPELL_PURIFY		:= 0x1F6;
const FX_SPELL_PURIFY		:= 0x36B0;
const SPEED_SPELL_PURIFY	:= 0x0a;
const LOOP_SPELL_PURIFY		:= 10;


// ** UnHoly Spells **
// Death Wail
const SPELL_ID_DEATHWAIL	:= 177;
const SFX_SPELL_DEATHWAIL	:= 0x180;
const SFX_SPELL_DEATHWAIL2	:= 0x183;
const FX_SPELL_DEATHWAIL	:= 0x374A;
const SPEED_SPELL_DEATHWAIL	:= 255;
const LOOP_SPELL_DEATHWAIL	:= 15;
// Commune With Living
const SPELL_ID_COMMUNEWITHLIVING:= 178;
const COMMUNEWITHLIVING_TEXT_COLOR := 54;
const COMMUNEWITHLIVING_TEXT_FONT := 3;
// Call the Dead
const SPELL_ID_CALLTHEDEAD	:= 179;
const SFX_SPELL_CALLTHEDEAD	:= 473;
// Necrolysis
const SPELL_ID_NECROLYSIS	:= 180;
const FX_SPELL_NECROLYSIS	:= 14154;
const SPEED_SPELL_NECROLYSIS	:= 255;
const LOOP_SPELL_NECROLYSIS	:= 15;
const SFX_SPELL_NECROLYSIS	:= 958;
// Fire Sense
const SPELL_ID_FIRESENSE	:= 181;
const SFX_SPELL_FIRESENSE	:= 0x346;
const FX_SPELL_FIRESENSE	:= 0x3709;
const SPEED_SPELL_FIRESENSE	:= 255;
const LOOP_SPELL_FIRESENSE	:= 15;
// Transfer Curse
const SPELL_ID_TRANSFERCURSE	:= 182;
const SFX_SPELL_TRANSFERCURSE	:= 0x39D;
const FX_SPELL_TRANSFERCURSE	:= 0x1F18;
const SPEED_SPELL_TRANSFERCURSE	:= 150;
const LOOP_SPELL_TRANSFERCURSE	:= 15;
// Fear Ritual
const SPELL_ID_FEARRITUAL	:= 183;
// Impaling Bones
const SPELL_ID_IMPALINGBONES	:= 184;
const SFX_SPELL_IMPALINGBONES	:= 0x1C8;
const FX_SPELL_IMPALINGBONES	:= 0x21FC;
const SPEED_SPELL_IMPALINGBONES	:= 20;
const LOOP_SPELL_IMPALINGBONES	:= 0;
// Death Pact
const SPELL_ID_DEATHPACT	:= 185;
const SFX_SPELL_DEATHPACT	:= 0x37A;
const FX_SPELL_DEATHPACT	:= 0x10FC;
const SPEED_SPELL_DEATHPACT	:= 255;
const LOOP_SPELL_DEATHPACT	:= 15;
// Demonic Skull
const SPELL_ID_DEMONICSKULL	:= 186;
const SFX_SPELL_DEMONICSKULL	:= 0x2A2;
const FX_SPELL_DEMONICSKULL	:= 0x2203;
const SPEED_SPELL_DEMONICSKULL	:= 5;
const LOOP_SPELL_DEMONICSKULL	:= 0;
const FX_SPELL_DEMONICSKULL2	:= 0x36D4;
// Create Pagan Reagent
const SPELL_ID_CREATEPAGANREAGENT:= 187;
const SFX_SPELL_CREATEPAGANREAGENT	:= 0x2BA;
const FX_SPELL_CREATEPAGANREAGENT	:= 0x3735;
const SPEED_SPELL_CREATEPAGANREAGENT	:= 7;
const LOOP_SPELL_CREATEPAGANREAGENT	:= 7;
// Greater Necrolysis
const SPELL_ID_GREATERNECROLYSIS:= 188;
const FX_SPELL_GREATERNECROLYSIS	:= 14154;
const SPEED_SPELL_GREATERNECROLYSIS	:= 255;
const LOOP_SPELL_GREATERNECROLYSIS	:= 15;
const SFX_SPELL_GREATERNECROLYSIS	:= 958;
// Summon Legion
const SPELL_ID_SUMMONLEGION	:= 189;
const SFX_SPELL_SUMMONLEGION	:= 0x217;
// Lava Stream
const SPELL_ID_LAVASTREAM	:= 190;
const SFX_SPELL_LAVASTREAM	:= 0x347;
const SFX_SPELL_LAVASTREAM2	:= 0x349;
const FX_SPELL_LAVASTREAM	:= 0x1A75;
const SPEED_SPELL_LAVASTREAM	:= 255;
const LOOP_SPELL_LAVASTREAM	:= 20;
// Apocalypse
const SPELL_ID_APOCALYPSE	:= 191;
const SFX_SPELL_APOCALYPSE	:= 0x347;
const SFX_SPELL_APOCALYPSE2	:= 0x34A;
const FX_SPELL_APOCALYPSE	:= 0x3709;
const SPEED_SPELL_APOCALYPSE	:= 0x0a;
const LOOP_SPELL_APOCALYPSE	:= 0x1e;
const FX_SPELL_APOCALYPSE2	:= 0x36d4;
const SPEED_SPELL_APOCALYPSE2	:= 5;
const LOOP_SPELL_APOCALYPSE2	:= 3;
const COLOR_SPELL_APOCALYPSE2	:= 1399;
// Gate to Hell
const SPELL_ID_GATETOHELL	:= 192;
const SFX_SPELL_GATETOHELL	:= 0x20F;
const FX_SPELL_GATETOHELL	:= 0x3709;
const SPEED_SPELL_GATETOHELL	:= 0x0a;
const LOOP_SPELL_GATETOHELL	:= 0x1e;

// ** Psionic Spells **
// Break wall
const SPELL_ID_BREAKWALL	:= 193;
const SFX_SPELL_BREAKWALL	:= 0x22E;
// Psychoportation
const SPELL_ID_PSYCHOPORTATION	:= 194;
const SFX_SPELL_PSYCHOPORTATION	:= 0xF6;
const FX_SPELL_PSYCHOPORTATION	:= 14186;
const SPEED_SPELL_PSYCHOPORTATION:= 255;
const LOOP_SPELL_PSYCHOPORTATION:= 17;
// Iron Shirt
const SPELL_ID_IRONSHIRT	:= 195;
const SFX_SPELL_IRONSHIRT	:= 0xF8;
const FX_SPELL_IRONSHIRT	:= 6899;
const SPEED_SPELL_IRONSHIRT	:= 255;
const LOOP_SPELL_IRONSHIRT	:= 13;
// Flying Fists
const SPELL_ID_FLYINGFISTS	:= 196;
const SFX_SPELL_FLYINGFISTS	:= 0x11D;
const FX_SPELL_FLYINGFISTS	:= 8281;
const SPEED_SPELL_FLYINGFISTS	:= 30;
const LOOP_SPELL_FLYINGFISTS	:= 0;
// Mind Call
const SPELL_ID_MINDCALL		:= 197;
const SFX_SPELL_MINDCALL	:= 0xF9;
const SFX_SPELL_MINDCALL2	:= 0x101;
const FX_SPELL_MINDCALL		:= 0x1FCB;
const SPEED_SPELL_MINDCALL	:= 255;
const LOOP_SPELL_MINDCALL	:= 12;
// Cleanse Thoughts
const SPELL_ID_CLEANSETHOUGHTS	:= 198;
const SFX_SPELL_CLEANSETHOUGHTS	:= 0xF8;
const FX_SPELL_CLEANSETHOUGHTS	:= 0x3728;
const SPEED_SPELL_CLEANSETHOUGHTS:= 255;
const LOOP_SPELL_CLEANSETHOUGHTS:= 15;
// Detect Brainwaves
const SPELL_ID_DETECTBRAINWAVES	:= 199;
const SFX_SPELL_DETECTBRAINWAVES:= 0x104;
// Mind Set
const SPELL_ID_MINDSET		:= 200;
const SFX_SPELL_MINDSET		:= 0x20D;
const FX_SPELL_MINDSET		:= 0x376A;
const SPEED_SPELL_MINDSET	:= 255;
const LOOP_SPELL_MINDSET	:= 15;
// Exhaustion
const SPELL_ID_EXHAUSTION	:= 201;
const SFX_SPELL_EXHAUSTION	:= 0x428;
const FX_SPELL_EXHAUSTION	:= 0x2AE4;
const SPEED_SPELL_EXHAUSTION	:= 255;
const LOOP_SPELL_EXHAUSTION	:= 13;
// Fists of Fury
const SPELL_ID_FISTSOFFURY	:= 202;
const SFX_SPELL_FISTSOFFURY	:= 0x11D;
const FX_SPELL_FISTSOFFURY	:= 8281;
const SPEED_SPELL_FISTSOFFURY	:= 30;
const LOOP_SPELL_FISTSOFFURY	:= 0;
// Mantra
const SPELL_ID_MANTRA		:= 203;
const SFX_SPELL_MANTRA	:= 0xF8;
const FX_SPELL_MANTRA	:= 0x1EE2;
const SPEED_SPELL_MANTRA:= 255;
const LOOP_SPELL_MANTRA	:= 14;
// Haunting Visions
const SPELL_ID_HAUNTINGVISIONS	:= 204;
const SFX_SPELL_HAUNTINGVISIONS	:= 0x382;
const FX_SPELL_HAUNTINGVISIONS	:= 0x374A;
const SPEED_SPELL_HAUNTINGVISIONS:= 255;
const LOOP_SPELL_HAUNTINGVISIONS:= 17;
// Clone
const SPELL_ID_CLONE		:= 205;
const SFX_SPELL_CLONE		:= 0x15E;
// Reincarnation
const SPELL_ID_REINCARNATION	:= 206;
const SFX_SPELL_REINCARNATION	:=0x216;
const FX_SPELL_REINCARNATION	:=0x1EE2;
const SPEED_SPELL_REINCARNATION	:= 255;
const LOOP_SPELL_REINCARNATION	:= 12;
// Hallucination
const SPELL_ID_HALLUCINATION	:= 207;
const SFX_SPELL_HALLUCINATION	:=0x15E;
const SFX_SPELL_HALLUCINATION2	:=0x318;
// Time Out
const SPELL_ID_TIMEOUT		:= 208;





// Miscellaneous functions for new class spells
function IsHostileOrNotGuild(mob, who)
	if (IsHostile(mob)) // a hostile npc
		return 1;
	endif
	if (! mob.acct) //an npc
		return 0;
	endif
	if (GetObjProperty(mob, "guild_id")!=GetObjProperty(who, "guild_id")) //player not in same guild
		return 1;
	endif
	return 0;	//player in same guild
endfunction

function IsGuildMemberOrAlly(mob, who)
	if (! mob.acct)
		return 0;
	endif
	var guild1id:=GetObjProperty(who, "guild_id");
	var guild2id:=GetObjProperty(mob, "guild_id");

	if (guild1id==guild2id)
		return 1;
	endif
	var guild1 := FindGuild(guild1id);
	var guild2 := FindGuild(guild2id);
	if (guild1.isallyguild(guild2))
		return 1;
	endif
	
	return 0;	
endfunction


//Calculate Very Small duration (eg para time), between 3 and 12 seconds
function calcVSmallDuration(skill, level)
	var initdur := 2;
	var skilldur := (skill / 20);
	var leveldur := (level / 2);
	var rtnval := CInt(initdur + skilldur + leveldur);

	return CInt(rtnval);
endfunction

//Calculate Small duration (eg leaves in binding nature), between 30 and 72 secs
function calcSmallDuration(skill, level)
	var initdur := 30;
	var skilldur := (skill / 5);
	var leveldur := (level * 2);
	var rtnval := CInt(initdur + skilldur + leveldur);
	
	return CInt(rtnval);
endfunction

// Calculate summoning duration, between 3 and 11min
function calcSummonDuration(skill, level)
	var initdur := 3 * 60;
	var skilldur := skill * 2;
	var leveldur := CDbl(level/2) * 60;
	var rtnval := CInt(initdur + skilldur + leveldur);

	return CInt(rtnval);
endfunction

// New spell calculations. 
// Calculate a long duration, between 5 and 16.5min
function calcLongDuration(skill, level)
	var initdur := 5 * 60;
	var skilldur := skill * 3;
	var leveldur := CDbl(level/2) * 60;
	var rtnval := CInt(initdur + skilldur + leveldur);

	return CInt(rtnval);
endfunction

// Calculate the damage range.
function calcDmgRange(caster, skillid)
	var range := (3 + GetEffectiveSkill(caster, skillid)/25);
	range := ModifyWithMagicEfficiency(caster, range);
	return CInt(range);
endfunction


