name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest ecompile
      run: |
        pushd /tmp
        wget -q https://github.com/polserver/polserver/releases/download/NightlyRelease/Nightly-Linux-clang.zip
        unzip Nightly-Linux-clang.zip
        rm -f *_dbg.zip
        rm -f Nightly-Linux-clang.zip
        unzip -j -o *.zip
        popd
        cp /tmp/ecompile scripts/
        cp /tmp/*.em scripts/
    - name: Compile
      run: |
        pushd setup
        ../scripts/ecompile -C ecompile.cfg
        popd
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: zuluhotelaustralia/zha/server
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true

  notify_discord:
    needs: build
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Discord notification ${{ needs.build.result }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: turleypol/actions-status-discord@master
        with:
          status: ${{ needs.build.result }}
          job: Build
          nofail: false